/*
 * This source file was generated by the Gradle 'init' task
 */
package game;

import game.rendering.GameWindow;

public class App {
    

    public static void main(String[] args) {
        new GameWindow();
    }
}
